runtime: nodejs22
env: standard

automatic_scaling:
  max_instances: 2

handlers:
  - url: /
    static_files: DreamHomeApp2/www/index.html
    upload: DreamHomeApp2/www/index.html

  - url: /(.*)
    static_files: DreamHomeApp2/www/\1
    upload: DreamHomeApp2/www/(.*)
