runtime: nodejs22
env: standard

service_account: app-engine-runtime@YOUR_PROJECT_ID.iam.gserviceaccount.com

handlers:
  - url: /
    static_files: DreamHomeApp2/dist/DreamHomeApp/index.html
    upload: DreamHomeApp2/dist/DreamHomeApp/index.html

  - url: /(.*)
    static_files: DreamHomeApp2/dist/DreamHomeApp/\1
    upload: DreamHomeApp2/dist/DreamHomeApp/(.*)
