runtime: nodejs20
env: standard

handlers:
  - url: /
    static_files: DreamHomeApp2/www/index.html
    upload: DreamHomeApp2/www/index.html

  - url: /(.*)
    static_files: DreamHomeApp2/www/\1
    upload: DreamHomeApp2/www/(.*)
