runtime: nodejs22
env: standard

service_account: app-engine-runtime@YOUR_PROJECT_ID.iam.gserviceaccount.com
handlers:
  - url: /
    static_files: www/index.html
    upload: www/index.html

  - url: /(.*)
    static_files: www/\1
    upload: www/(.*)
