steps:
  - name: "node:22"
    dir: "DreamHomeApp2"
    entrypoint: "npm"
    args: ["install"]

  - name: "node:22"
    dir: "DreamHomeApp2"
    entrypoint: "npm"
    args: ["run", "build"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--quiet"]

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1200s"
