# Defines the Cloud Build CI/CD pipeline

steps:
  # Step 1: Install dependencies
  - name: "node:22"
    # Run commands inside the Angular project directory
    dir: "DreamHomeApp2"
    entrypoint: "npm"
    args: ["install"]

  # Step 2: Build the Angular/Ionic application
  - name: "node:22"
    dir: "DreamHomeApp2"
    entrypoint: "npm"
    args: ["run", "build"]

  # Step 3: Deploy the built application to App Engine
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--quiet"]

# Logging configuration
options:
  # Sends logs to Google Cloud Logging
  logging: CLOUD_LOGGING_ONLY

# Maximum time allowed for the build process
timeout: "1200s"
