steps:
  # Step 1: Install dependencies
  - name: "node:22"
    entrypoint: "npm"
    args: ["install"]

  # Step 2: Build the app
  - name: "node:22"
    entrypoint: "npm"
    args: ["run", "build"]

  # Step 3: Deploy to App Engine
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--quiet"]

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1200s"
